# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f38dc4ebbab59968edfff0c19b50514a2e67f5c4d55041c015cf51631fd758e8c7a538961d58c3f991e0f885728a0d2fdb938b6d18c5da48cb57e97c4b52b5dc

test:
  secret_key_base: fa3097ce031f9b48e66e1a98340c9995c334c4edf0d29ff392f8e11d7d10acd05a6f0adbc78e94120ab52b49f60ddb17041a57811e691b633ffdea4f22cdbfbb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
